apiVersion: v1
kind: Service

metadata:
  name: passin-service
  labels:
    app: passin

spec:
  selector:
    app: passin
  type: ClusterIP
  ports:
  - name: passin-service
    port: 80  #porta do nosso servi√ßo
    targetPort: 3333 #porta do container
    protocol: TCP